/**
 * paic-mark.ts — PAIC hero mark traced from public/paic-logo.png.
 *
 * Geometry is generated by scripts/trace-paic-mark.py (mesh nodes/edges,
 * shield outline). Icon paths (gear, varsity P/M, mountain) are hand-placed
 * to match the raster logo. Animation mirrors brain-mark.ts: edges and
 * nodes assemble, wordmark and details fade last.
 */

import {
  PAIC_EDGES,
  PAIC_NODES,
  PAIC_OUTLINE,
  PAIC_WORD,
  PAIC_WORD_POS,
} from "./paic-mark-data";

/** [d, delayClass] — detail paths fade after the mesh assembles. */
const DETAILS: ReadonlyArray<readonly [string, string]> = [
  [
    "M17 15.5a2.2 2.2 0 1 0 0 4.4 2.2 2.2 0 0 0 0-4.4zm0-2.8v1.4m0 8.4v1.4m-5.6-5.6h1.4m8.4 0h1.4m-1.1-4.9-.9 1m-4.3 4.3-.9 1m0-6.4.9 1m4.3 4.3.9 1",
    "bmark__detail--gear",
  ],
  [
    "M44 78.5L50 70l6 8.5H44zm4.2-5.2c.8 1.2 1.6 1.2 2.4 0",
    "bmark__detail--mountain",
  ],
  [
    "M36.5 86v-9.5h3.4c2.5 0 4 1.3 4 3.2 0 1.4-.8 2.4-2.1 2.8 1.6.4 2.6 1.5 2.6 3.1 0 2.3-1.7 3.6-4.5 3.6h-3.4zm2.3-8.2h1.1c1.1 0 1.7-.5 1.7-1.4s-.6-1.3-1.7-1.3h-1.1v2.7zm0 6h1.3c1.2 0 2-.5 2-1.5s-.8-1.5-2-1.5h-1.3v3zm8.8-6h2.3l2.9 5.7 2.9-5.7h2.3v9.5h-2.2v-6.1l-3 6.1h-1.7l-3-6.1v6.1h-2.2v-9.5zm12.2 0h2.4l3 5.9 3-5.9h2.4v9.5h-2.2v-6.1l-3.1 6.1h-1.7l-3.1-6.1v6.1h-2.2v-9.5z",
    "bmark__detail--m",
  ],
  [
    "M73.5 48.5v-9.5h5c3.7 0 6 2.1 6 5.5 0 2.3-1.1 4-2.9 4.8 1.9.8 3 2.4 3 4.7 0 3.5-2.5 5.8-6.4 5.8h-4.7zm2.3-11.2v4.4h2.5c1.7 0 2.6-.8 2.6-2.2s-.9-2.2-2.6-2.2h-2.5zm0 6.7v4.6h2.7c1.9 0 2.9-.9 2.9-2.3s-1-2.3-2.9-2.3h-2.7z",
    "bmark__detail--p",
  ],
] as const;

const WORD_SPAN = 28;

function escapeXml(v: string): string {
  return v
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildPaicMarkSvg(reduce: boolean): string {
  const outline = PAIC_OUTLINE[0];
  const [wordX, wordY] = PAIC_WORD_POS;
  const fontSize =
    Math.round((WORD_SPAN / (0.85 * PAIC_WORD.length)) * 10) / 10;

  const edges = PAIC_EDGES.map(([a, b], i) => {
    const [x1, y1] = PAIC_NODES[a];
    const [x2, y2] = PAIC_NODES[b];
    const delay = reduce ? 0 : 0.3 + i * 0.012;
    const len = Math.hypot(x2 - x1, y2 - y1).toFixed(2);
    return `<line class="bmark__edge" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" style="--d:${delay}s;--len:${len}" />`;
  }).join("");

  const nodes = PAIC_NODES.map(([x, y, r, hollow], i) => {
    const delay = reduce ? 0 : 0.12 + i * 0.022;
    return `<circle class="bmark__node${hollow ? " bmark__node--hollow" : ""}" cx="${x}" cy="${y}" r="${r}" style="--d:${delay}s" />`;
  }).join("");

  const details = DETAILS.map(([d, cls], i) => {
    const delay = reduce ? 0 : 1.05 + i * 0.08;
    return `<path class="bmark__detail ${cls}" d="${d}" style="--d:${delay}s" />`;
  }).join("");

  const word = `<text class="bmark__word" x="${wordX}" y="${wordY}" text-anchor="middle"
      dominant-baseline="central" font-size="${fontSize}">${escapeXml(PAIC_WORD)}</text>`;

  return `
<svg class="bmark bmark--paic${reduce ? " bmark--static" : ""}" viewBox="0 0 100 100" aria-hidden="true" focusable="false">
  <defs>
    <linearGradient id="bmark-grad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="var(--color-primary, #1A64B7)" />
      <stop offset="55%" stop-color="var(--color-primary, #1A64B7)" />
      <stop offset="100%" stop-color="var(--color-accent, #F58113)" />
    </linearGradient>
    <linearGradient id="bmark-grad-warm" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="var(--color-accent, #F58113)" />
      <stop offset="100%" stop-color="var(--color-accent, #F58113)" />
    </linearGradient>
  </defs>
  <polygon class="bmark__outline" points="${outline}" />
  <g class="bmark__edges">${edges}</g>
  <g class="bmark__nodes">${nodes}</g>
  ${word}
  <g class="bmark__details">${details}</g>
</svg>`;
}

export function renderPaicMark(el: Element | null): void {
  if (!el) return;

  const reduce =
    typeof window !== "undefined" &&
    window.matchMedia &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  el.innerHTML = buildPaicMarkSvg(reduce);
}
